# 调试模式开关
debug-mode: false

# 可用的光源物品列表
light-items:
  - TORCH
  - SOUL_TORCH
  - REDSTONE_TORCH
  - LANTERN
  - SOUL_LANTERN
  - GLOWSTONE
  - SEA_LANTERN
  - SHROOMLIGHT
  - REDSTONE_LAMP
  - BEACON
  - END_ROD
  - FROGLIGHT
  - OCHRE_FROGLIGHT
  - VERDANT_FROGLIGHT
  - PEARLESCENT_FROGLIGHT
  - GLOW_INK_SAC
  - GLOW_ITEM_FRAME
  - GLOW_BERRIES
  - GLOW_LICHEN
  - JACK_O_LANTERN 